require 'spec_helper'
require_relative '../../../../helpers/unit/provider/arcgis_rest_shared_examples'

describe Puppet::Type.type(:arcgis_directory).provider(:ruby) do
  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) { os_facts }
    end
  end

  describe 'instances' do
    it 'should have an instance method' do
      expect(described_class).to respond_to :instances
    end
  end

  describe 'prefetch' do
    it 'should have a prefetch method' do
      expect(described_class).to respond_to :prefetch
    end
  end

  let(:name) { 'arcgisoutput' }

  let(:list_empty) do
    {
      directories: [
      ]
    }
  end

  let(:list_empty_expected) { [] }

  let(:list_success) do
    {
      directories: [
        {
          name: 'arcgisoutput',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgisoutput',
          directoryType: 'OUTPUT',
          cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
          maxFileAge: 10,
          description: 'Stores various information generated by services, such as map images.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgisoutput'
        },
        {
          name: 'arcgisjobs',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgisjobs',
          directoryType: 'JOBS',
          cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
          maxFileAge: 360,
          description: 'Stores results and other information from geoprocessing services.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgisjobs'
        },
        {
          name: 'arcgiscache',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgiscache',
          directoryType: 'CACHE',
          cleanupMode: 'NONE',
          maxFileAge: 0,
          description: 'Stores tile caches used by map, globe, and image services for rapid performance.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgiscache'
        },
        {
          name: 'arcgisuploads',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem/arcgisuploads',
          directoryType: 'UPLOADS',
          cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
          maxFileAge: 1440,
          description: 'Stores items uploaded to ArcGIS Server during publishing from a remote server.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgisuploads'
        },
        {
          name: 'arcgisinput',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem/arcgisinput',
          directoryType: 'INPUT',
          cleanupMode: 'NONE',
          maxFileAge: 0,
          description: 'Stores source files (such as maps and data) for services that you publish.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgisinput'
        },
        {
          name: 'kml',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem/kml',
          directoryType: 'KML',
          cleanupMode: 'NONE',
          maxFileAge: 0,
          description: 'Stores files used by KML network links published on ArcGIS Server.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/kml'
        },
        {
          name: 'arcgisindex',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem/arcgisindex',
          directoryType: 'INDEX',
          cleanupMode: 'NONE',
          maxFileAge: 0,
          description: 'Stores indexes of data locations used by the search service.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgisindex'
        },
        {
          name: 'arcgisjobregistry',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem/arcgisjobregistry',
          directoryType: 'JOBREGISTRY',
          cleanupMode: 'NONE',
          maxFileAge: 0,
          description: 'Stores files that are used internally by the GIS server.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgisjobregistry'
        },
        {
          name: 'arcgissystem',
          physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem',
          directoryType: 'SYSTEM',
          cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
          maxFileAge: 1440,
          description: 'Stores directories and files used internally by ArcGIS Server.',
          useLocalDir: 'false',
          localDirectoryPath: '',
          virtualPath: '/rest/directories/arcgissystem'
        }
      ]
    }
  end

  let(:list_success_expected) do
    [
      {
        name: 'arcgisoutput',
        physicalPath: '/opt/arcgis/server/usr/directories/arcgisoutput',
        directoryType: 'OUTPUT',
        cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
        maxFileAge: 10,
        description: 'Stores various information generated by services, such as map images.',
        useLocalDir: 'false',
        localDirectoryPath: '',
        virtualPath: '/rest/directories/arcgisoutput'
      },
      {
        name: 'arcgisjobs',
        physicalPath: '/opt/arcgis/server/usr/directories/arcgisjobs',
        directoryType: 'JOBS',
        cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
        maxFileAge: 360,
        description: 'Stores results and other information from geoprocessing services.',
        useLocalDir: 'false',
        localDirectoryPath: '',
        virtualPath: '/rest/directories/arcgisjobs'
      },
      {
        name: 'arcgiscache',
        physicalPath: '/opt/arcgis/server/usr/directories/arcgiscache',
        directoryType: 'CACHE',
        cleanupMode: 'NONE',
        maxFileAge: 0,
        description: 'Stores tile caches used by map, globe, and image services for rapid performance.',
        useLocalDir: 'false',
        localDirectoryPath: '',
        virtualPath: '/rest/directories/arcgiscache'
      },
      {
        name: 'arcgissystem',
        physicalPath: '/opt/arcgis/server/usr/directories/arcgissystem',
        directoryType: 'SYSTEM',
        cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
        maxFileAge: 1440,
        description: 'Stores directories and files used internally by ArcGIS Server.',
        useLocalDir: 'false',
        localDirectoryPath: '',
        virtualPath: '/rest/directories/arcgissystem'
      }
    ]
  end

  let(:retrieve_success) do
    {
      name: 'arcgisoutput',
      physicalPath: '/opt/arcgis/server/usr/directories/arcgisoutput',
      directoryType: 'OUTPUT',
      cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
      maxFileAge: 10,
      description: 'Stores various information generated by services, such as map images.',
      useLocalDir: 'false',
      localDirectoryPath: '',
      virtualPath: '/rest/directories/arcgisoutput'
    }
  end

  let(:retrieve_noitem) do
    {
      status: "error",
      messages: [
        "Could not find resource or operation 'arcgisoutput' on the system."
      ],
      code: 404
    }
  end

  let(:create_success) do
    {
      status: "success",
      messages: []
    }
  end

  let(:update_success) do
    {
      status: "success",
      messages: []
    }
  end

  let(:delete_success) do
    {
      status: "success"
    }
  end

  let(:create_resource) { Puppet::Type::Arcgis_directory.new create_props }
  let(:create_provider) { described_class.new create_resource }
  let(:create_props) do
    {
      name: 'arcgisoutput',
      physicalPath: '/opt/arcgis/server/usr/directories/arcgisoutput',
      directoryType: 'OUTPUT',
      cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
      maxFileAge: 10,
      description: 'Stores various information generated by services, such as map images.',
    }
  end

  let(:update_resource) { Puppet::Type::Arcgis_directory.new update_props }
  let(:update_provider) { described_class.new update_resource }
  let(:update_props) do
    {
      name: 'arcgisoutput',
      physicalPath: '/opt/arcgis/server/usr/directories/arcgisoutput_updated',
      directoryType: 'OUTPUT',
      cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
      maxFileAge: 10,
      description: 'Stores various information generated by services, such as map images.',
    }
  end

  let(:delete_resource) { Puppet::Type::Arcgis_directory.new delete_props }
  let(:delete_provider) { described_class.new delete_resource }
  let(:delete_props) do
    {
      ensure: 'absent',
      name: 'arcgisoutput',
      physicalPath: '/opt/arcgis/server/usr/directories/arcgisoutput',
      directoryType: 'OUTPUT',
      cleanupMode: 'TIME_ELAPSED_SINCE_LAST_MODIFIED',
      maxFileAge: 10,
      description: 'Stores various information generated by services, such as map images.',
    }
  end

  include_examples 'REST API', 'admin/system/directories', 'register', 'edit', 'unregister', false
end
